version: "3"

networks:
  main-net:

volumes:
  dbdata:

services:
  postgres-main2:
    image: postgres:latest
    container_name: "postgres-main2"
    restart: always
    networks:
      - main-net
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  api-nodejs:
    image: node:latest
    container_name: "api-nodejs"
    restart: always
    command: ["npm", "start"]
    environment: 
      NODE_ENV: dev
      PGHOST: 'postgres-main2'
      PGDATABASE: 'postgres'
      PGUSER: 'postgres'
      PGPASSWORD: 'postgres'
    ports:
      - "81:51515"
    working_dir: /home/app
    networks:
      - main-net
    depends_on:
      - postgres-main2
    volumes:
      - "./api-nodejs:/home/app"